version: "3.9"

services:
  mpmc-dev:
    image: mpmc-dev
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: ["sleep", "infinity"]

